include:
  - ./authServer/docker-compose.auth-server.yaml
  - ./playbackServer/docker-compose.playback-server.yaml
services:
  nginx:
    image: tiangolo/nginx-rtmp:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./stream-volume:/hls/live
    ports:
      - "1935:1935"
    depends_on:
      auth-server:
        condition: service_healthy
  postgres:
    image: postgres
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "streamkeys"
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s