services:
  playback-server:
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "8001:8001"
    depends_on:
      auth-server:
        condition: service_healthy
      nginx:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ../stream-volume:/hls/live